/**
 * DUELPVP client — VRF (ORAO) edition, hardened.
 *
 * create_duel -> join_duel (deposit + request randomness) -> settle_duel.
 * The joiner generates fresh random `force` at join time, so no one can
 * pre-create the randomness PDA or learn the outcome in advance.
 */
import * as anchor from "@coral-xyz/anchor";
import { BN, Program } from "@coral-xyz/anchor";
import { Connection, PublicKey, SystemProgram } from "@solana/web3.js";
import { randomBytes } from "@noble/hashes/utils";
import {
  Orao,
  networkStateAccountAddress,
  randomnessAccountAddress,
} from "@orao-network/solana-vrf";
import type { Duelpvp } from "../target/types/duelpvp";

export type DuelProgram = Program<Duelpvp>;

export const TREASURY_SEED = "treasury";
export const DUEL_SEED = "duel";

// ---------------------------------------------------------------------------
// PDA derivation
// ---------------------------------------------------------------------------

export function deriveTreasuryPda(programId: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync([Buffer.from(TREASURY_SEED)], programId);
}

export function deriveDuelPda(
  gameId: BN,
  creator: PublicKey,
  programId: PublicKey
): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(DUEL_SEED), gameId.toArrayLike(Buffer, "le", 8), creator.toBuffer()],
    programId
  );
}

export function generateGameId(): BN {
  return new BN(randomBytes(8), "le");
}

/** Fresh 32-byte VRF seed generated by the joiner. Never reuse one. */
export function generateForce(): Uint8Array {
  return randomBytes(32);
}

/** Unbiased d6 derivation (rejection sampling), mirrors the on-chain logic. */
export function deriveDice(randomness: Uint8Array): {
  creator: [number, number];
  opponent: [number, number];
} {
  const faces: number[] = [];
  for (let i = 0; i < randomness.length && faces.length < 4; i++) {
    if (randomness[i] < 252) faces.push((randomness[i] % 6) + 1);
  }
  while (faces.length < 4) faces.push((randomness[0] % 6) + 1);
  return { creator: [faces[0], faces[1]], opponent: [faces[2], faces[3]] };
}

// ---------------------------------------------------------------------------
// Win condition
// ---------------------------------------------------------------------------

export type WinCondition = { higherWins: {} } | { lowerWins: {} };
export const HIGHER_WINS: WinCondition = { higherWins: {} };
export const LOWER_WINS: WinCondition = { lowerWins: {} };

// ---------------------------------------------------------------------------
// Admin
// ---------------------------------------------------------------------------

const BPF_LOADER_UPGRADEABLE = new PublicKey(
  "BPFLoaderUpgradeab1e11111111111111111111111"
);

export function deriveProgramDataPda(programId: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync(
    [programId.toBuffer()],
    BPF_LOADER_UPGRADEABLE
  )[0];
}

/** Run ONCE after deploy, signed by the program's upgrade authority (deployer). */
export async function initializeTreasury(program: DuelProgram, admin: PublicKey) {
  const [treasury] = deriveTreasuryPda(program.programId);
  return program.methods
    .initializeTreasury()
    .accounts({
      admin,
      treasury,
      programData: deriveProgramDataPda(program.programId),
      systemProgram: SystemProgram.programId,
    })
    .rpc();
}

export async function setPaused(program: DuelProgram, admin: PublicKey, paused: boolean) {
  const [treasury] = deriveTreasuryPda(program.programId);
  return program.methods.setPaused(paused).accounts({ admin, treasury }).rpc();
}

export async function setMaxBet(program: DuelProgram, admin: PublicKey, maxBetLamports: BN) {
  const [treasury] = deriveTreasuryPda(program.programId);
  return program.methods.setMaxBet(maxBetLamports).accounts({ admin, treasury }).rpc();
}

// ---------------------------------------------------------------------------
// Game flow
// ---------------------------------------------------------------------------

export async function createDuel(
  program: DuelProgram,
  creator: PublicKey,
  gameId: BN,
  betLamports: BN,
  winCondition: WinCondition,
  requiredOpponent: PublicKey | null,
  joinTimeoutSeconds: number | null = null
) {
  const [duel] = deriveDuelPda(gameId, creator, program.programId);
  const [treasury] = deriveTreasuryPda(program.programId);
  await program.methods
    .createDuel(
      gameId,
      betLamports,
      winCondition,
      requiredOpponent,
      joinTimeoutSeconds === null ? null : new BN(joinTimeoutSeconds)
    )
    .accounts({ creator, duel, treasury, systemProgram: SystemProgram.programId })
    .rpc();
  return { duel, gameId };
}

/**
 * Opponent joins: deposits the matching bet + requests VRF in one tx.
 * Generates fresh random `force`. Does a balance pre-flight so the tx doesn't
 * fail mid-flight if the wallet can't cover bet + VRF fee + tx fees.
 */
export async function joinDuel(
  program: DuelProgram,
  connection: Connection,
  opponent: PublicKey,
  creator: PublicKey,
  gameId: BN
) {
  const vrf = new Orao(program.provider as anchor.AnchorProvider);
  const [duel] = deriveDuelPda(gameId, creator, program.programId);
  const duelAcc = await program.account.duel.fetch(duel);

  const ns = await vrf.getNetworkState();
  const vrfFee: BN = ns.config.requestFee as BN;
  const bet: BN = duelAcc.betLamports as BN;
  const needed = bet.add(vrfFee).add(new BN(10_000_000)); // + headroom for tx/rent
  const balance = await connection.getBalance(opponent);
  if (new BN(balance).lt(needed)) {
    throw new Error(
      `Insufficient balance: need ~${needed.toString()} lamports (bet + VRF fee + fees), have ${balance}.`
    );
  }

  const force = generateForce();
  const random = randomnessAccountAddress(Buffer.from(force));

  await program.methods
    .joinDuel(gameId, Array.from(force))
    .accounts({
      opponent,
      creator,
      duel,
      vrfConfig: networkStateAccountAddress(),
      vrfTreasury: ns.config.treasury,
      random,
      vrf: vrf.programId,
      systemProgram: SystemProgram.programId,
    })
    .rpc();

  return { duel, random, force };
}

/** Wait until ORAO fulfils (the ~1-3s "rolling" window). */
export async function waitForRandomness(
  program: DuelProgram,
  random: PublicKey
): Promise<Uint8Array> {
  const vrf = new Orao(program.provider as anchor.AnchorProvider);
  const r = await vrf.waitFulfilled(random.toBuffer());
  return Uint8Array.from(r.randomness);
}

/**
 * Permissionless settle. Does NOT touch the treasury — the 1% fee stays in the
 * duel escrow and is swept to the treasury later on `close`. This keeps settles
 * fully parallel across thousands of concurrent duels (no shared write-lock).
 */
export async function settleDuel(
  program: DuelProgram,
  caller: PublicKey,
  creator: PublicKey,
  opponent: PublicKey,
  gameId: BN
) {
  const [duel] = deriveDuelPda(gameId, creator, program.programId);
  const duelAcc = await program.account.duel.fetch(duel);
  return program.methods
    .settleDuel(gameId)
    .accounts({
      caller,
      creator,
      opponent,
      duel,
      random: duelAcc.randomness as PublicKey,
    })
    .rpc();
}

/**
 * Close / refund (see program docs for the three paths). Also sweeps the
 * accrued house fee to the treasury on the Settled path. Requires the duel's
 * `randomness` account: on the Rolling (stuck-VRF) refund path the program
 * verifies it matches and is NOT yet fulfilled, so a determined-but-unsettled
 * duel can never be refunded out from under the winner.
 */
export async function closeDuel(
  program: DuelProgram,
  caller: PublicKey,
  creator: PublicKey,
  gameId: BN,
  opponent?: PublicKey
) {
  const [duel] = deriveDuelPda(gameId, creator, program.programId);
  const [treasury] = deriveTreasuryPda(program.programId);
  const duelAcc = await program.account.duel.fetch(duel);
  // duel.randomness is Pubkey::default() (system program) until someone joins;
  // that's fine — the program only enforces it on the Rolling path.
  const random = duelAcc.randomness as PublicKey;
  return program.methods
    .closeDuel(gameId)
    .accounts({
      caller,
      creator,
      opponent: opponent ?? creator,
      treasury,
      random,
      duel,
    })
    .rpc();
}

/** Creator cancels their own unmatched duel and gets refunded. */
export async function cancelUnmatchedDuel(
  program: DuelProgram,
  creator: PublicKey,
  gameId: BN
) {
  return closeDuel(program, creator, creator, gameId);
}

// ---------------------------------------------------------------------------
// Reads + realtime
// ---------------------------------------------------------------------------

export async function fetchDuel(program: DuelProgram, duel: PublicKey) {
  return program.account.duel.fetch(duel);
}

export function subscribeDuelEvents(
  program: DuelProgram,
  handlers: {
    onCreated?: (e: any) => void;
    onJoined?: (e: any) => void;
    onSettled?: (e: any) => void;
    onClosed?: (e: any) => void;
  }
): number[] {
  const ids: number[] = [];
  const add = (name: string, cb?: (e: any) => void) => {
    if (cb) ids.push(program.addEventListener(name as any, cb));
  };
  add("duelCreated", handlers.onCreated);
  add("duelJoined", handlers.onJoined);
  add("duelSettled", handlers.onSettled);
  add("duelClosed", handlers.onClosed);
  return ids;
}
